apiVersion: v1
kind: Service
metadata:
  name: systems-api
  labels:
    app: systems-api
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: systems-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systems-api
  labels:
    app: systems-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systems-api
  template:
    metadata:
      labels:
        app: systems-api
    spec:
      initContainers:
      - name: systems-api-db-setup
        image: systems-api
        env:
          - name: DB_NAME
            value: 'et_api_production'
          - name: RAVEN_DSN
            value: 'https://929365547a42468fb521248a96100646:139af8327fa340b88088efeae059fca8@sentry.io/1254109'
          - name: DB_HOST
            value: db
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            value: postgres
          - name: REDIS_URL
            value: "redis://redis:6379/2"
          - name: SECRET_KEY_BASE
            value: sdlkjewfkjhfviuhduihenrjk435r89esfd7cv983qh2n4r3q27yh4u5rtfg
        command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 $DB_HOST $DB_PORT && nc -zvw1 redis 6379 && bundle exec rails db:create db:migrate db:seed && exit 0 || sleep 3; done ;exit 1"]
      containers:
      - name: systems-api
        image: systems-api
        ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping.json
            port: 8080
          initialDelaySeconds: 40
          timeoutSeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /ping.json
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 30
        env:
          - name: DB_NAME
            value: 'et_api_production'
          - name: RAVEN_DSN
            value: 'https://929365547a42468fb521248a96100646:139af8327fa340b88088efeae059fca8@sentry.io/1254109'
          - name: DB_HOST
            value: db
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            value: postgres
          - name: REDIS_URL
            value: "redis://redis:6379/2"
          - name: SECRET_KEY_BASE
            value: sdlkjewfkjhfviuhduihenrjk435r89esfd7cv983qh2n4r3q27yh4u5rtfg
      - name: systems-api-sidekiq
        image: systems-api
        ports:
          - name: http
            containerPort: 7433
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 7433
          initialDelaySeconds: 65
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7433
          initialDelaySeconds: 70
          periodSeconds: 14
        env:
          - name: DB_NAME
            value: 'et_api_production'
          - name: RAVEN_DSN
            value: 'https://929365547a42468fb521248a96100646:139af8327fa340b88088efeae059fca8@sentry.io/1254109'
          - name: DB_HOST
            value: db
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            value: postgres
          - name: REDIS_URL
            value: "redis://redis:6379/2"
          - name: SECRET_KEY_BASE
            value: sdlkjewfkjhfviuhduihenrjk435r89esfd7cv983qh2n4r3q27yh4u5rtfg
        command:
        - "./run_sidekiq.sh"
